version: "3"
services:
  api:
    build: 
      context: .
    ports: 
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
  postgres:
    image: "postgres:10"
    volumes:
      - "~/programming/databases/ecommerce-demo-data:/var/lib/postgresql/data"
